-- MySQL Script generated by MySQL Workbench
-- Wed May 15 11:05:18 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `User_ID` INT(9) UNSIGNED ZEROFILL NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Sex` VARCHAR(10) NOT NULL,
  `Born` DATE NOT NULL,
  `Nick_Name` VARCHAR(45) NULL,
  `Major` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(45) NULL,
  `communicate` VARCHAR(45) NULL,
  `Name_Access` TINYINT NOT NULL DEFAULT 0,
  `Sex_Access` TINYINT NOT NULL DEFAULT 0,
  `Born_Access` TINYINT NOT NULL DEFAULT 0,
  `Major_Access` TINYINT NOT NULL DEFAULT 0,
  `Address_Access` TINYINT NOT NULL DEFAULT 0,
  `Communicate_Access` TINYINT NOT NULL DEFAULT 0,
  UNIQUE INDEX `peopleid_UNIQUE` (`User_ID` ASC) VISIBLE,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evaluation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation` (
  `Evaluation_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(45) NULL,
  `Time` DATETIME NOT NULL,
  `Level` INT NOT NULL,
  PRIMARY KEY (`Evaluation_ID`),
  UNIQUE INDEX `unique` (`Content` ASC, `Time` ASC, `Level` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activity` (
  `Activity_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Activity_Name` VARCHAR(45) NOT NULL,
  `Start_Time` DATETIME NOT NULL,
  `End_Time` DATETIME NOT NULL,
  `Approver_ID` INT NULL,
  `Response_ID` INT NOT NULL,
  `Range` TINYINT(1) NOT NULL,
  `State` TINYINT NOT NULL,
  PRIMARY KEY (`Activity_ID`),
  UNIQUE INDEX `Approver_Resp_Unique` (`Approver_ID` ASC, `Response_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Club` (
  `Club_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Club_Name` VARCHAR(45) NOT NULL,
  `Club_Type` VARCHAR(45) NOT NULL,
  `Club_Intro` VARCHAR(200) NULL,
  `Club_Leader` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`Club_ID`),
  UNIQUE INDEX `Club_Name_UNIQUE` (`Club_Name` ASC) VISIBLE,
  INDEX `Leader_idx` (`Club_Leader` ASC) VISIBLE,
  CONSTRAINT `Club_Leader`
    FOREIGN KEY (`Club_Leader`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department_ID` INT UNSIGNED NOT NULL,
  `Introduction` VARCHAR(200) NULL,
  `Father_Club_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Department_ID`),
  INDEX `Father_Club_ID_idx` (`Father_Club_ID` ASC) VISIBLE,
  CONSTRAINT `Department_Father_Club_ID`
    FOREIGN KEY (`Father_Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Work`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Work` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Work` (
  `User_ID` INT UNSIGNED ZEROFILL NOT NULL,
  `Club_ID` INT UNSIGNED NOT NULL,
  `Authority` INT UNSIGNED NOT NULL,
  `Work_Name` VARCHAR(45) NOT NULL,
  `Department_ID` INT UNSIGNED NULL,
  PRIMARY KEY (`User_ID`, `Club_ID`),
  INDEX `connectP_idx` (`User_ID` ASC) VISIBLE,
  INDEX `nnnn_idx` (`Club_ID` ASC) VISIBLE,
  INDEX `Department_ID_idx` (`Department_ID` ASC) VISIBLE,
  CONSTRAINT `Work_User_ID`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Work_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Work_Department_ID`
    FOREIGN KEY (`Department_ID`)
    REFERENCES `mydb`.`Department` (`Department_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity-Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activity-Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activity-Club` (
  `Club_ID` INT UNSIGNED NOT NULL,
  `Activity_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Club_ID`, `Activity_ID`),
  INDEX `Activity_ID_idx` (`Activity_ID` ASC) INVISIBLE,
  INDEX `Club_ID_idx` (`Club_ID` ASC) VISIBLE,
  CONSTRAINT `AC_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AC_Activity_ID`
    FOREIGN KEY (`Activity_ID`)
    REFERENCES `mydb`.`Activity` (`Activity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Activity_User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Activity_User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Activity_User` (
  `Activity_ID` INT UNSIGNED NOT NULL,
  `User_ID` INT UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`Activity_ID`, `User_ID`),
  INDEX `User_ID_idx` (`User_ID` ASC) INVISIBLE,
  CONSTRAINT `AU_Activity_ID`
    FOREIGN KEY (`Activity_ID`)
    REFERENCES `mydb`.`Activity` (`Activity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AU_User_ID`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item` (
  `Item_ID` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `Item_Name` VARCHAR(45) NOT NULL,
  `Item_Value` INT UNSIGNED NULL,
  `Loan_State` TINYINT NOT NULL,
  PRIMARY KEY (`Item_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item_Loan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item_Loan` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item_Loan` (
  `Item_ID` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `User_ID` INT UNSIGNED ZEROFILL NOT NULL,
  `Start_Time` DATETIME NOT NULL,
  `End_Time` DATETIME NOT NULL,
  `Return_Time` DATETIME NULL,
  PRIMARY KEY (`Item_ID`, `User_ID`),
  INDEX `User_ID_idx` (`User_ID` ASC) VISIBLE,
  CONSTRAINT `Item_ID`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `mydb`.`Item` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `User_ID`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Item_Belong`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Item_Belong` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Item_Belong` (
  `Item_ID` INT(5) UNSIGNED ZEROFILL NOT NULL,
  `Club_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Item_ID`, `Club_ID`),
  INDEX `Club_ID_idx` (`Club_ID` ASC) VISIBLE,
  CONSTRAINT `IB_Item_ID`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `mydb`.`Item` (`Item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IB_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Apply_To_Studert`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Apply_To_Studert` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Apply_To_Studert` (
  `Apply_ID` INT UNSIGNED NOT NULL,
  `Apply_Type` VARCHAR(45) NOT NULL,
  `Apply_From` INT UNSIGNED ZEROFILL NOT NULL,
  `Apply_To` INT UNSIGNED NOT NULL,
  `Apply_Description` VARCHAR(100) NULL,
  PRIMARY KEY (`Apply_ID`),
  INDEX `Apply_From_idx` (`Apply_From` ASC) VISIBLE,
  CONSTRAINT `AS_Apply_From`
    FOREIGN KEY (`Apply_From`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `AS_Apply_To`
    FOREIGN KEY (`Apply_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Admin` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `Admin_ID` INT UNSIGNED NOT NULL,
  `Admin_Account` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`Admin_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluation_Activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evaluation_Activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation_Activity` (
  `From` INT UNSIGNED ZEROFILL NOT NULL,
  `To` INT UNSIGNED NOT NULL,
  `Evaluation_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Evaluation_ID`),
  INDEX `From_idx` (`From` ASC) INVISIBLE,
  INDEX `To_idx` (`To` ASC) VISIBLE,
  CONSTRAINT `EA_From`
    FOREIGN KEY (`From`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EA_To`
    FOREIGN KEY (`To`)
    REFERENCES `mydb`.`Activity` (`Activity_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EA_Evaluation`
    FOREIGN KEY (`Evaluation_ID`)
    REFERENCES `mydb`.`Evaluation` (`Evaluation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Announcement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Announcement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Announcement` (
  `Announcement_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Content` VARCHAR(200) NOT NULL,
  `Time` DATETIME NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Club_ID` INT UNSIGNED NOT NULL,
  `Publisher` INT UNSIGNED NULL,
  PRIMARY KEY (`Announcement_ID`),
  INDEX `Club_ID_idx` (`Club_ID` ASC) VISIBLE,
  INDEX `Publisher_idx` (`Publisher` ASC) VISIBLE,
  CONSTRAINT `Announcement_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Announcement_Publisher`
    FOREIGN KEY (`Publisher`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tutor_Club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tutor_Club` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tutor_Club` (
  `Tutor_ID` INT UNSIGNED ZEROFILL NOT NULL,
  `Club_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Tutor_ID`, `Club_ID`),
  INDEX `Club_ID_idx` (`Club_ID` ASC) VISIBLE,
  INDEX `Tutor_ID_idx` (`Tutor_ID` ASC) VISIBLE,
  CONSTRAINT `TC_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TC_Tutor_ID`
    FOREIGN KEY (`Tutor_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluation_Member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Evaluation_Member` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation_Member` (
  `Member_ID` INT UNSIGNED NOT NULL,
  `Evaluation_ID` INT UNSIGNED NOT NULL,
  `Club_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Member_ID`, `Evaluation_ID`, `Club_ID`),
  INDEX `Evaluation_ID_idx` (`Evaluation_ID` ASC) VISIBLE,
  INDEX `Club_ID_idx` (`Club_ID` ASC) VISIBLE,
  CONSTRAINT `EM_Member_ID`
    FOREIGN KEY (`Member_ID`)
    REFERENCES `mydb`.`User` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EM_Evaluation_ID`
    FOREIGN KEY (`Evaluation_ID`)
    REFERENCES `mydb`.`Evaluation` (`Evaluation_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EM_Club_ID`
    FOREIGN KEY (`Club_ID`)
    REFERENCES `mydb`.`Club` (`Club_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
